### ISSUE TITLE
Which mining algorithm is used ?

### ISSUE THREAD

**Issue by serkserk** [gertjanssenswillen/processmapR#34]
Hi,

I was wondering which mining algorithm do you use to plot your process_map ?
And is there any way to change it ?

Thanks

**Comment by gertjanssenswillen** [comment]
Hi Serkan

Process map doesn't uses a discovery algorithm, it just shows an directed graph of all the follows-relations in the event log. This means an edge is shown between every two consecutive activity instances (even if the following activity happens while the first is not finished yet). In case there are multiple instances starting at the same timestamp, it uses the order as defined by the eventlog function (order of the data, alphabetical, or otherwise).

In case of more questions, don't hesitate to contact me.
