### ISSUE TITLE
precedence_matrix with performance views

### ISSUE THREAD

**Issue by frkbr** [gertjanssenswillen/processmapR#39]
The `precedence_matrix()` is sometimes the better alternative than a `process_map()`in case of a "spaghetti-process" with many variants. It would therefore be useful to have a performance view for the precedence diagrams too.

This would have the same syntax as the `process_map` function, e.g. 

`precedence_matrix(performance(median, "days"))` and its other options.

**Comment by gertjanssenswillen** [comment]
I think it is a great idea to use the same syntax as for process map, both from development as from a user perspective. Once the process_map function has been refactored (see also #40), I'll take a look at this.

I'll just have to take into account back-ward compatibility. One option will be to keep the precedence matrix as-is (at least for now), and create a new function in the generic way. I'll keep you updated.

**Comment by frkbr** [comment]
👍

**Comment by gertjanssenswillen** [comment]
github now contains a function process_matrix (next to precedence matrix). Process matrix accepts the same frequency() and performance() configurations as process_map. 

Further testing still needed, and also performance of the new function is low because it uses the process map code which should be improved

**Comment by frkbr** [comment]
Thanks for the new function!
